# Generated by Django 3.1.2 on 2020-10-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='datanascimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
