# Generated by Django 3.1.2 on 2020-10-27 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_datanascimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutosComprados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.TextField()),
                ('preco', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
            options={
                'verbose_name_plural': 'Produtos comprados',
            },
        ),
    ]
