# Generated by Django 3.1.2 on 2020-10-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201027_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='identidade',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ultimo_nome',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='estadocivil',
            name='descricao',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produtocomprado',
            name='preco',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sexo',
            name='descricao',
            field=models.CharField(max_length=30),
        ),
    ]
