# Generated by Django 3.1.2 on 2020-10-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201028_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtocomprado',
            name='preco',
            field=models.IntegerField(verbose_name='Preço'),
        ),
    ]
