# Generated by Django 3.1.2 on 2020-10-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201028_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='datanascimento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(max_length=30, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ultimo_nome',
            field=models.CharField(max_length=30, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=30, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.IntegerField(verbose_name='Preço'),
        ),
    ]
